[package]
name = "rs-playground"
version = "0.1.0"
authors = ["Shane Osbourne <shane.osbourne8@gmail.com>"]

[dependencies]
regex = "1.0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
void = "1.0.2"
from_file = "0.1.3"
from_file_derive = "0.1.3"